// Generated by CoffeeScript 1.4.0
(function() {

  test('can create a DataTable from a single record, and it has one row', function() {
    var dt, record;
    record = {
      a: 1,
      b: 2,
      c: 3
    };
    dt = new Psy.DataTable.fromRecords([record]);
    return equal(dt.nrow(), 1);
  });

  test('can create a DataTable from a two records, and it has two rows', function() {
    var dt, records;
    records = [
      {
        a: 1,
        b: 2,
        c: 3
      }, {
        a: 1,
        b: 2,
        c: 3
      }
    ];
    dt = new Psy.DataTable.fromRecords(records);
    return equal(dt.nrow(), 2);
  });

  test('can create a DataTable from a two records, with partially overlapping keys', function() {
    var dt, records;
    records = [
      {
        a: 1,
        b: 2,
        c: 3
      }, {
        b: 2,
        c: 3,
        x: 7
      }
    ];
    dt = new Psy.DataTable.fromRecords(records);
    equal(dt.ncol(), 4);
    return equal(dt.nrow(), 2);
  });

}).call(this);
