// Generated by CoffeeScript 1.6.3
(function() {
  var MousePress, Q, Response, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Q = require("q");

  Response = require("../stimresp").Response;

  MousePress = (function(_super) {
    __extends(MousePress, _super);

    function MousePress() {
      _ref = MousePress.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    MousePress.prototype.activate = function(context) {
      var deferred, mouse,
        _this = this;
      deferred = Q.defer();
      mouse = context.mousepressStream();
      mouse.stream.take(1).onValue(function(event) {
        mouse.stop();
        return deferred.resolve(event);
      });
      return deferred.promise;
    };

    return MousePress;

  })(Response);

  exports.MousePress = MousePress;

}).call(this);
