// Generated by CoffeeScript 1.6.3
(function() {
  var Prompt, Q, Response, utils, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  utils = require("../utils");

  Q = require("q");

  Response = require("../stimresp").Response;

  Prompt = (function(_super) {
    __extends(Prompt, _super);

    function Prompt() {
      _ref = Prompt.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Prompt.prototype.defaults = {
      title: "Prompt",
      delay: 0,
      defaultValue: "",
      theme: 'vex-theme-wireframe'
    };

    Prompt.prototype.activate = function(context) {
      var deferred, promise,
        _this = this;
      deferred = Q.defer();
      promise = Q.delay(this.spec.delay);
      promise.then(function(f) {
        return vex.dialog.prompt({
          message: _this.spec.title,
          placeholder: _this.spec.defaultValue,
          className: 'vex-theme-wireframe',
          callback: function(value) {
            return deferred.resolve(value);
          }
        });
      });
      return deferred.promise;
    };

    return Prompt;

  })(Response);

  exports.Prompt = Prompt;

}).call(this);
