// Generated by CoffeeScript 1.6.3
(function() {
  var Background, Stimulus,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Stimulus = require("../../stimresp").Stimulus;

  Background = (function(_super) {
    __extends(Background, _super);

    function Background(stims, fill) {
      this.stims = stims != null ? stims : [];
      this.fill = fill != null ? fill : "white";
      Background.__super__.constructor.call(this, {}, {});
    }

    Background.prototype.render = function(context, layer) {
      var background, stim, _i, _len, _ref, _results;
      background = new Kinetic.Rect({
        x: 0,
        y: 0,
        width: context.width(),
        height: context.height(),
        name: 'background',
        fill: this.fill
      });
      layer.add(background);
      _ref = this.stims;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        stim = _ref[_i];
        _results.push(stim.render(context, layer));
      }
      return _results;
    };

    return Background;

  })(Stimulus);

  exports.Background = Background;

}).call(this);
