// Generated by CoffeeScript 1.6.3
(function() {
  var Clear, Stimulus, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Stimulus = require("../../stimresp").Stimulus;

  Clear = (function(_super) {
    __extends(Clear, _super);

    function Clear() {
      _ref = Clear.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Clear.prototype.render = function(context, layer) {
      return context.clearContent(true);
    };

    return Clear;

  })(Stimulus);

  exports.Clear = Clear;

}).call(this);
