// Generated by CoffeeScript 1.6.3
(function() {
  var FixationCross, Stimulus, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Stimulus = require("../../stimresp").Stimulus;

  FixationCross = (function(_super) {
    __extends(FixationCross, _super);

    function FixationCross() {
      _ref = FixationCross.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    FixationCross.prototype.defaults = {
      strokeWidth: 8,
      length: 150,
      fill: 'black'
    };

    FixationCross.prototype.render = function(context, layer) {
      var group, horz, vert, x, y;
      x = context.width() / 2;
      y = context.height() / 2;
      horz = new Kinetic.Rect({
        x: x - this.spec.length / 2,
        y: y,
        width: this.spec.length,
        height: this.spec.strokeWidth,
        fill: this.spec.fill
      });
      vert = new Kinetic.Rect({
        x: x - this.spec.strokeWidth / 2,
        y: y - this.spec.length / 2 + this.spec.strokeWidth / 2,
        width: this.spec.strokeWidth,
        height: this.spec.length,
        fill: this.spec.fill
      });
      group = new Kinetic.Group();
      group.add(horz);
      group.add(vert);
      return layer.add(group);
    };

    return FixationCross;

  })(Stimulus);

  exports.FixationCross = FixationCross;

}).call(this);

/*
//@ sourceMappingURL=fixationcross.map
*/
