// Generated by CoffeeScript 1.6.3
(function() {
  var Rectangle, Stimulus,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Stimulus = require("../../stimresp").Stimulus;

  Rectangle = (function(_super) {
    __extends(Rectangle, _super);

    Rectangle.prototype.defaults = {
      x: 0,
      y: 0,
      width: 100,
      height: 100,
      fill: 'red'
    };

    function Rectangle(spec) {
      if (spec == null) {
        spec = {};
      }
      Rectangle.__super__.constructor.call(this, spec);
    }

    Rectangle.prototype.render = function(context, layer) {
      var coords, rect;
      coords = this.computeCoordinates(context, this.spec.position, this.spec.width, this.spec.height);
      rect = new Kinetic.Rect({
        x: coords[0],
        y: coords[1],
        width: this.spec.width,
        height: this.spec.height,
        fill: this.spec.fill,
        stroke: this.spec.stroke,
        strokeWidth: this.spec.strokeWidth
      });
      return layer.add(rect);
    };

    return Rectangle;

  })(Stimulus);

  exports.Rectangle = Rectangle;

}).call(this);
