// Generated by CoffeeScript 1.6.3
(function() {
  var Stimulus, Text, layout,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Stimulus = require("../../stimresp").Stimulus;

  layout = require("../../layout");

  Text = (function(_super) {
    __extends(Text, _super);

    Text.prototype.defaults = {
      content: "Text",
      x: 5,
      y: 5,
      width: null,
      fill: "black",
      fontSize: 40,
      fontFamily: "Arial",
      lineHeight: 2,
      textAlign: "center",
      position: null
    };

    function Text(spec) {
      if (spec == null) {
        spec = {};
      }
      Text.__super__.constructor.call(this, spec);
      if (_.isArray(this.spec.content)) {
        this.spec.content = this.spec.content.join("\n");
      }
    }

    Text.prototype.render = function(context, layer) {
      var coords, text;
      text = new Kinetic.Text({
        x: 0,
        y: 0,
        text: this.spec.content,
        fontSize: this.spec.fontSize,
        fontFamily: this.spec.fontFamily,
        fill: this.spec.fill,
        lineHeight: this.spec.lineHeight,
        width: this.spec.width,
        listening: false,
        align: this.spec.textAlign
      });
      coords = this.computeCoordinates(context, this.spec.position, text.getWidth(), text.getHeight());
      text.setPosition({
        x: coords[0],
        y: coords[1]
      });
      return layer.add(text);
    };

    return Text;

  })(Stimulus);

  exports.Text = Text;

}).call(this);
