// Generated by CoffeeScript 1.6.3
(function() {
  var HtmlLink, html,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  html = require("./html");

  HtmlLink = (function(_super) {
    __extends(HtmlLink, _super);

    HtmlLink.prototype.defaults = {
      label: "link"
    };

    function HtmlLink(spec) {
      if (spec == null) {
        spec = {};
      }
      HtmlLink.__super__.constructor.call(this, spec);
      this.html = $("<a href='#'>" + this.spec.label + "</a>");
      this.el.append(this.html);
      this.positionElement(this.el);
    }

    return HtmlLink;

  })(html.HtmlStimulus);

  exports.HtmlLink = HtmlLink;

}).call(this);
