// Generated by CoffeeScript 1.6.3
(function() {
  var HtmlButton, html,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  html = require("./html");

  HtmlButton = (function(_super) {
    __extends(HtmlButton, _super);

    HtmlButton.prototype.defaults = {
      label: "Next",
      "class": ""
    };

    function HtmlButton(spec) {
      if (spec == null) {
        spec = {};
      }
      HtmlButton.__super__.constructor.call(this, spec);
      this.el.addClass("ui button");
      this.el.addClass(this.spec["class"]);
      this.el.append(this.spec.label);
      this.positionElement(this.el);
    }

    return HtmlButton;

  })(html.HtmlStimulus);

  exports.HtmlButton = HtmlButton;

}).call(this);

/*
//@ sourceMappingURL=htmlbutton.map
*/
