// Generated by CoffeeScript 1.6.3
(function() {
  var HtmlRange, html,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  html = require("./html");

  HtmlRange = (function(_super) {
    __extends(HtmlRange, _super);

    HtmlRange.prototype.defaults = {
      min: 0,
      max: 100,
      value: 0,
      step: 1,
      height: 100,
      width: 300
    };

    function HtmlRange(spec) {
      if (spec == null) {
        spec = {};
      }
      HtmlRange.__super__.constructor.call(this, spec);
      this.input = $("<input type='range'>");
      this.input.attr({
        min: this.spec.min,
        max: this.spec.max,
        value: this.spec.value,
        step: this.spec.step
      });
      this.input.css({
        width: this.spec.width
      });
      this.el.append(this.input);
    }

    return HtmlRange;

  })(html.Stimulus);

  exports.HtmlRange = HtmlRange;

}).call(this);
