// Generated by CoffeeScript 1.6.3
(function() {
  var Html, HtmlResponse, HtmlStimulus, Response, Stimulus, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Stimulus = require("../../stimresp").Stimulus;

  Response = require("../../stimresp").Response;

  HtmlStimulus = (function(_super) {
    __extends(HtmlStimulus, _super);

    HtmlStimulus.prototype.tag = "div";

    HtmlStimulus.prototype.div = function() {
      return $(document.createElement("div"));
    };

    function HtmlStimulus(spec) {
      HtmlStimulus.__super__.constructor.call(this, spec);
      this.el = document.createElement(this.tag);
      this.el = $(this.el);
    }

    HtmlStimulus.prototype.positionElement = function(el) {
      if ((this.spec.x != null) && (this.spec.y != null)) {
        return el.css({
          position: "absolute",
          left: this.spec.x,
          top: this.spec.y
        });
      }
    };

    HtmlStimulus.prototype.centerElement = function(el) {
      return el.css({
        margin: "0 auto",
        position: "absolute",
        left: "50%",
        top: "50%"
      });
    };

    HtmlStimulus.prototype.render = function(context, layer) {
      return context.appendHtml(this.el);
    };

    return HtmlStimulus;

  })(Stimulus);

  HtmlResponse = (function(_super) {
    __extends(HtmlResponse, _super);

    function HtmlResponse() {
      _ref = HtmlResponse.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    HtmlResponse.include(Response);

    return HtmlResponse;

  })(HtmlStimulus);

  exports.HtmlStimulus = HtmlStimulus;

  exports.HtmlResponse = HtmlResponse;

  Html = {};

  Html.HtmlButton = require("./htmlbutton").HtmlButton;

  Html.HtmlLink = require("./htmllink").HtmlLink;

  Html.HtmlIcon = require("./htmlicon").HtmlIcon;

  Html.Instructions = require("./instructions").Instructions;

  Html.Markdown = require("./markdown").Markdown;

  Html.Message = require("./message").Message;

  Html.Page = require("./page").Page;

  exports.Html = Html;

}).call(this);
