// Generated by CoffeeScript 1.6.3
(function() {
  var Instructions, Markdown, Q, html, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  html = require("./html");

  Q = require("q");

  Markdown = require("./markdown").Markdown;

  _ = require('lodash');

  Instructions = (function(_super) {
    __extends(Instructions, _super);

    function Instructions(spec) {
      var content, div, i, itm, key, md, type, value;
      if (spec == null) {
        spec = {};
      }
      Instructions.__super__.constructor.call(this, spec);
      this.pages = (function() {
        var _ref, _results;
        _ref = this.spec.pages;
        _results = [];
        for (key in _ref) {
          value = _ref[key];
          type = _.keys(value)[0];
          content = _.values(value)[0];
          md = new Markdown(content);
          div = this.div();
          div.addClass("ui stacked segment").append(md.el);
          _results.push(div);
        }
        return _results;
      }).call(this);
      this.menu = this.div();
      this.menu.addClass("ui borderless pagination menu");
      this.back = $("<a class=\"item\">\n  <i class=\"icon left arrow\"></i>  Previous\n </a>").attr("id", "instructions_back");
      this.next = $("<a class=\"item\">\nNext <i class=\"icon right arrow\"></i>\n</a>").attr("id", "instructions_next");
      this.menu.append(this.back).append("\n");
      this.items = (function() {
        var _i, _ref, _results;
        _results = [];
        for (i = _i = 1, _ref = this.pages.length; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
          itm = $("<a class=\"item\">" + i + "</a>");
          this.menu.append(itm).append("\n");
          _results.push(itm);
        }
        return _results;
      }).call(this);
      this.items[0].addClass("active");
      this.menu.append(this.next).css("position", "absolute").css("right", "15px");
      this.currentPage = 0;
      this.el.append(this.pages[this.currentPage]);
      this.el.append(this.menu);
    }

    Instructions.prototype.activate = function(context) {
      this.deferred = Q.defer();
      return this.deferred.promise;
    };

    Instructions.prototype.updateEl = function(currentPage) {
      this.el.empty();
      this.el.append(this.pages[this.currentPage]);
      return this.el.append(this.menu);
    };

    Instructions.prototype.render = function(context, layer) {
      var _this = this;
      this.next.click(function(e) {
        if (_this.currentPage < (_this.pages.length - 1)) {
          _this.items[_this.currentPage].removeClass("active");
          _this.currentPage += 1;
          _this.items[_this.currentPage].addClass("active");
          _this.updateEl(_this.currentPage);
          return _this.render(context);
        } else {
          return _this.deferred.resolve(0);
        }
      });
      this.back.click(function(e) {
        console.log("back click!");
        if (_this.currentPage > 0) {
          _this.items[_this.currentPage].removeClass("active");
          _this.currentPage -= 1;
          _this.items[_this.currentPage].addClass("active");
          _this.updateEl(_this.currentPage);
          return _this.render(context);
        }
      });
      if (this.currentPage > 0) {
        this.back.removeClass("disabled");
      }
      $(this.pages[this.currentPage]).css({
        "min-height": context.height() - 50
      });
      return context.appendHtml(this.el);
    };

    return Instructions;

  })(html.HtmlResponse);

  exports.Instructions = Instructions;

}).call(this);
