// Generated by CoffeeScript 1.6.3
(function() {
  var Message, html,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  html = require("./html");

  Message = (function(_super) {
    __extends(Message, _super);

    Message.prototype.defaults = {
      title: "Message!",
      content: "your content here",
      color: "",
      size: "large"
    };

    function Message(spec) {
      if (spec == null) {
        spec = {};
      }
      Message.__super__.constructor.call(this, spec);
      this.el.addClass(this.messageClass());
      this.title = $("<div>" + this.spec.title + "</div>").addClass("header");
      this.content = $("<p>" + this.spec.content + "</p>");
      this.el.append(this.title);
      this.el.append(this.content);
    }

    Message.prototype.messageClass = function() {
      return "ui message " + this.spec.color + " " + this.spec.size;
    };

    return Message;

  })(html.HtmlStimulus);

  exports.Message = Message;

}).call(this);

/*
//@ sourceMappingURL=message.map
*/
