// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var Exp, exp, Psy;
  Psy = require('./PsyCloud');
  Exp = require('./Elements');
  this.LexDesign = {
    Design: {
      Variables: {
        Crossed: {
          wordtype: {
            type: 'Factor',
            levels: [
              'word',
              'nonword'
            ]
          },
          syllables: {
            type: 'Factor',
            levels: [
              1,
              2
            ]
          }
        }
      },
      Structure: {
        type: 'Block',
        blocks: 8,
        reps_per_block: 4
      }
    },
    ItemSet: {
      words: {
        type: 'text',
        items: [
          'hello',
          'goodbye',
          'flirg',
          'schmirt',
          'black',
          'sweetheart',
          'grum',
          'snirg',
          'snake',
          'pet',
          'hirble',
          'kerble'
        ],
        attributes: {
          wordtype: [
            'word',
            'word',
            'nonword',
            'nonword',
            'word',
            'word',
            'nonword',
            'nonword',
            'word',
            'word',
            'nonword',
            'nonword'
          ],
          syllables: [
            2,
            2,
            1,
            1,
            1,
            2,
            1,
            1,
            1,
            1,
            2,
            2
          ]
        },
        sampler: { type: 'Exhaustive' }
      }
    },
    Display: {
      Trial: function (trial) {
        return {
          1: {
            FixationCross: {
              length: 100,
              strokeWidth: 5,
              Next: { Timeout: 2e3 }
            }
          },
          2: {
            Text: {
              content: trial.words,
              position: 'center'
            },
            Next: {
              KeyPressed: {
                keys: [
                  'a',
                  'b'
                ],
                correct: trial.wordtype === 'word' ? 'a' : 'b',
                timeout: 3e3
              }
            }
          }
        };
      }
    }
  };
  exp = new Psy.Experiment(this.LexDesign, new Exp.KineticStimFactory);
  exp.start();
}.call(this);
