// Generated by CoffeeScript 1.6.3
(function() {
  var Dots, Exp, Psy, Q, datatable, design, html, include, kinetic, layout, lib, libs, samplers, stimresp, utils, _, _i, _len;

  Exp = require("./elements");

  Psy = require("./psycloud");

  Dots = require("./dotmotion");

  utils = require("./utils");

  datatable = require("./datatable");

  samplers = require("./samplers");

  stimresp = require("./stimresp");

  layout = require("./layout");

  design = require("./design");

  kinetic = require("./components/kinetic/kinetic");

  html = require("./components/html/html");

  _ = require('lodash');

  Q = require("q");

  include = function(lib) {
    var key, value, _results;
    _results = [];
    for (key in lib) {
      value = lib[key];
      _results.push(exports[key] = value);
    }
    return _results;
  };

  libs = [Exp, Psy, Dots, utils, datatable, samplers, stimresp, layout, design, kinetic, html];

  for (_i = 0, _len = libs.length; _i < _len; _i++) {
    lib = libs[_i];
    include(lib);
  }

  exports.Q = Q;

  exports._ = _;

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
