// Generated by CoffeeScript 1.6.3
(function() {
  var Dots, Exp, Psy, key, value;

  Exp = require("./Elements");

  Psy = require("./PsyCloud");

  Dots = require("./DotMotion");

  for (key in Psy) {
    value = Psy[key];
    exports[key] = value;
  }

  for (key in Exp) {
    value = Exp[key];
    exports[key] = value;
  }

  for (key in Dots) {
    value = Dots[key];
    exports[key] = value;
  }

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
